# Generated by Django 3.0.8 on 2020-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=32)),
                ('owner', models.CharField(max_length=32)),
                ('displayURL', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('established', models.CharField(max_length=4)),
                ('languages', models.IntegerField()),
                ('sitelink', models.CharField(max_length=80)),
                ('applink', models.CharField(max_length=80)),
            ],
        ),
    ]
