# Generated by Django 3.0.8 on 2020-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='attcoverage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='atteaseofuse',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='attprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='attreputation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
