# Generated by Django 3.0.8 on 2020-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_article_showonhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='descaccessibilitycontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descavailabilitycontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descfeaturescontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descoverviewcontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descpaymentcontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descpricingcontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descreputationcontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descsdealscontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descservicecontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='descsummarycontent',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
