# Generated by Django 3.0.8 on 2020-09-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200903_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='genericlinkcarrentals',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinkcruises',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinkflights',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinkhotels',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinktickets',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinktours',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinktrains',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='genericlinktransfers',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
