# Generated by Django 3.0.8 on 2020-09-03 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200903_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='descaccessibilitycontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descavailabilitycontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descfeaturescontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descoverviewcontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descpaymentcontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descpricingcontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descreputationcontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descsdealscontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descservicecontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='descsummarycontent',
        ),
        migrations.RemoveField(
            model_name='site',
            name='paymentamex',
        ),
        migrations.RemoveField(
            model_name='site',
            name='paymentapplepay',
        ),
        migrations.RemoveField(
            model_name='site',
            name='paymentgooglepay',
        ),
        migrations.RemoveField(
            model_name='site',
            name='paymentmastercard',
        ),
        migrations.RemoveField(
            model_name='site',
            name='paymentpaypal',
        ),
        migrations.RemoveField(
            model_name='site',
            name='paymentvisa',
        ),
        migrations.CreateModel(
            name='SiteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descoverviewcontent', models.CharField(default='', max_length=2000)),
                ('descfeaturescontent', models.CharField(default='', max_length=2000)),
                ('descpricingcontent', models.CharField(default='', max_length=2000)),
                ('descavailabilitycontent', models.CharField(default='', max_length=2000)),
                ('descaccessibilitycontent', models.CharField(default='', max_length=2000)),
                ('descpaymentcontent', models.CharField(default='', max_length=2000)),
                ('descreputationcontent', models.CharField(default='', max_length=2000)),
                ('descservicecontent', models.CharField(default='', max_length=2000)),
                ('descsummarycontent', models.CharField(default='', max_length=2000)),
                ('descsdealscontent', models.CharField(default='', max_length=2000)),
                ('paymentvisa', models.BooleanField(default=False)),
                ('paymentmastercard', models.BooleanField(default=False)),
                ('paymentamex', models.BooleanField(default=False)),
                ('paymentpaypal', models.BooleanField(default=False)),
                ('paymentapplepay', models.BooleanField(default=False)),
                ('paymentgooglepay', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.Product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='main.Site')),
            ],
        ),
    ]
