# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200903_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproduct',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Product'),
        ),
    ]
