# Generated by Django 3.0.8 on 2020-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200920_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproduct',
            name='switchdeals',
            field=models.BooleanField(default=False),
        ),
    ]
