# Generated by Django 3.0.8 on 2020-11-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
                ('description', models.CharField(default='', max_length=200)),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='main.Redirect')),
            ],
        ),
    ]
