# Generated by Django 3.0.8 on 2020-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_redirect_trackingclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='applink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sitelink',
            field=models.CharField(max_length=250),
        ),
    ]
