# Generated by Django 3.0.8 on 2020-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200720_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='prodcarrentals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodcruises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodflights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodhotels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodtickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodtours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodtrains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='prodtransfers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='attcoverage',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='atteaseofuse',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='attprice',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='attreputation',
            field=models.IntegerField(default=50),
        ),
    ]
