# Generated by Django 3.0.8 on 2020-07-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200720_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logofilename',
            field=models.CharField(default='bookinglogo130.png', max_length=50),
            preserve_default=False,
        ),
    ]
