# Generated by Django 3.0.8 on 2020-12-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_destinationgeo_otadestinationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='qAndA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField(max_length=4000)),
                ('slug', models.SlugField(max_length=100)),
                ('ota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qasites', to='main.Site')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaproducts', to='main.Product')),
            ],
        ),
    ]
