# Generated by Django 3.0.8 on 2020-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_site_logofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='applink',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
