# Generated by Django 3.0.8 on 2021-01-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210102_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanda',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.qAndATag'),
        ),
    ]
