# Generated by Django 3.0.8 on 2020-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_site_bgimagefilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('sort', models.IntegerField()),
            ],
        ),
    ]
