# Generated by Django 3.0.8 on 2021-01-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210102_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='qanda',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
