# Generated by Django 3.0.8 on 2020-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200825_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnailfilename',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
