# Generated by Django 3.0.8 on 2021-01-11 11:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_qanda_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fulltext',
            field=ckeditor.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
    ]
