# Generated by Django 3.0.8 on 2021-01-11 11:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_article_fulltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fulltext',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
