# Generated by Django 3.0.8 on 2021-01-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210111_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='article',
            name='updatedate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
