# Generated by Django 3.0.8 on 2020-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200830_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='paymentamex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='paymentapplepay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='paymentgooglepay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='paymentmastercard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='paymentpaypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='paymentvisa',
            field=models.BooleanField(default=False),
        ),
    ]
