# Generated by Django 3.0.8 on 2021-01-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210117_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='showheader',
            field=models.BooleanField(default=True),
        ),
    ]
