# Generated by Django 3.0.8 on 2021-01-31 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article_showheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='similararticles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Article'),
        ),
    ]
