# Generated by Django 3.0.8 on 2021-01-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_article_similararticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='similararticles',
        ),
        migrations.AddField(
            model_name='article',
            name='similararticles',
            field=models.ManyToManyField(blank=True, related_name='_article_similararticles_+', to='main.Article'),
        ),
    ]
