# Generated by Django 3.0.8 on 2021-02-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210131_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproduct',
            name='descovertablecontent',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
