# Generated by Django 3.0.8 on 2021-02-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_siteproduct_descovertablecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproduct',
            name='descovertablecontent',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
