# Generated by Django 3.0.8 on 2021-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210207_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproduct',
            name='descovertablecontent',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
