# Generated by Django 3.0.8 on 2020-09-07 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200906_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('daterecorded', models.DateField(default=datetime.date.today, unique=True)),
                ('pricingrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='main.PricingRecord')),
            ],
        ),
    ]
