# Generated by Django 3.0.8 on 2021-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210207_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ismeta',
            field=models.BooleanField(default=False),
        ),
    ]
