# Generated by Django 3.0.8 on 2020-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_price_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrecord',
            name='price7days',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
