# Generated by Django 3.0.8 on 2020-09-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200907_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproduct',
            name='spcoverage',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='siteproduct',
            name='speaseofuse',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='siteproduct',
            name='spprice',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='siteproduct',
            name='sppriceraw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteproduct',
            name='spreputation',
            field=models.IntegerField(default=50),
        ),
    ]
