# Generated by Django 3.0.8 on 2020-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200908_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seodescription',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='seokeywords',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
